### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by kusky3** [rust-motd/rust-motd#3] opened 2021-10-02 08:33 UTC
error while running cargo build on the latest version

error[E0597]: `current_regex` does not live long enough
  --> src/components/fail_2_ban.rs:46:18

**Comment by MarcelRobitaille** [comment] 2021-10-02 14:28
Cannot reproduce on `cargo 1.49.0 (d00d64df9 2020-12-05)`. Could you please specify your version?

**Comment by kusky3** [comment] 2021-10-02 16:25
cargo 1.55.0 on armv7l

**Comment by MarcelRobitaille** [comment] 2021-10-02 16:31
Thank you for your report. We will look into it.

**Comment by MarcelRobitaille** [comment] 2021-10-04 03:39
Fixed in fc77515

**Closed by MarcelRobitaille** 2021-10-04 03:39 UTC
